/*
 * Macro.h
 *
 *  Created on: May 9, 2014
 *      Author: root
 */

#ifndef MACRO_H_
#define MACRO_H_



const int CLIENT_LOGIN = 4007;


const int ROBOT_HEART_BEAT = 2002;
const int ROBOT_NOTIFY_ROBOT_ONLINE_RESPONSE = 2003;
const int ROBOT_LOGIN = 2004;
const int ROBOT_REBUILD_VPN = 4008;
const int ROBOT_BUILD_VPN_TCP = 2015;
const int ROBOT_BUILD_VPN_UDP = 2016;
const int ROBOT_BUILD_VPN_RESPONSE = 2017;
const int ROBOT_NOTIFY_ROBOT_ONLINE = 4003;
const int ROBOT_ALARM = 4005;

const int USER_CHECK_ROBOT_VALIDATION = 5001;
const int USER_GET_CAPTCHA = 5002;
const int USER_CHECK_CAPTCHA = 5003;
const int USER_SET_USER_INFO = 5004;
const int USER_LOGIN = 5005;
const int USER_LOGOUT = 5006;
const int USER_SEARCH_BOUND_ROBOTS_INFO = 5009;
const int USER_DELETE_BOUND_ROBOT_INFO = 5011;
const int USER_SEARCH_BOUND_USERS_INFO = 5012;
const int USER_CHOOSE_ROBOT = 5014;
const int USER_BUILD_VPN_TCP = 5015;
const int USER_BUILD_VPN_UDP = 5016;
const int USER_SEARCH_ROBOT_ALARM_SETTINGS = 5017;
const int USER_MODIFY_ROBOT_ALARM_SETTINGS = 5018;
const int USER_CHANGE_PASSWORD = 5019;
const int USER_CHANGE_ROBOT_LOCATION = 5020;
const int USER_SEARCH_ROBOT_LOCATION = 5021;
const int USER_DELETE_BOUND_USER = 5022;
const int USER_ADD_ROBOT = 5023;
const int USER_REQUEST_HISTORY = 5024;
const int USER_PROCESS_ALARM_RESULT = 5025;

const int USER_REBUILD_VPN = 4009;


#endif /* MACRO_H_ */
